### ISSUE TITLE
Sequelize with MySQL of  feathers generate service

### ISSUE THREAD

**Issue by ricaragao** [feathersjs-ecosystem/feathers-sequelize#249]
Hi,

I create two services using **_feathers generate service_** to use sequelize with mysql.
Works fine, but when I try associate many-to-many (or others), I have these errors:

```
> feathers-bapi@0.0.1 start /home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi
> node src/

/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/sequelize/lib/associations/mixin.js:37
      throw new Error(this.name + '.belongsToMany called with something that\'s not a subclass of Sequelize.Model');
      ^

Error: bweb_user.belongsToMany called with something that's not a subclass of Sequelize.Model
    at Function.belongsToMany (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/sequelize/lib/associations/mixin.js:37:13)
    at Function.bwebusers.associate (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/src/models/bwebusers.model.js:47:15)
    at Object.keys.forEach.name (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/src/sequelize.js:62:22)
    at Array.forEach (<anonymous>)
    at Function.app.setup (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/src/sequelize.js:60:25)
    at Function.app.setup (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/@feathersjs/authentication/lib/index.js:58:27)
    at Function.app.setup (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/@feathersjs/authentication-jwt/lib/index.js:79:27)
    at Function.app.setup (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/@feathersjs/authentication-local/lib/index.js:44:27)
    at Function.listen (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/@feathersjs/express/lib/index.js:63:12)
    at Function.newMethod (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/uberproto/lib/proto.js:34:20)
    at Function.listen (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/@feathersjs/socketio/lib/index.js:37:25)
    at Function.newMethod [as listen] (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/node_modules/uberproto/lib/proto.js:34:20)
    at Object.<anonymous> (/home/ricardo.aragao@target.local/disk2/Desenvolvimento/workspaces/node/feathers-bapi/src/index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

My Models:

```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function(app) {
  const sequelizeClient = app.get('sequelizeClient');
  const bwebusers = sequelizeClient.define(
    'bweb_user',
    {
      userid: {
        type: DataTypes.BIGINT(20).UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
        unique: true
      },
      username: { type: DataTypes.STRING(100), allowNull: false, unique: true },
      use_acl: { type: DataTypes.BOOLEAN, defaultValue: false },
      enabled: { type: DataTypes.BOOLEAN, defaultValue: true },
      comment: { type: DataTypes.STRING, defaultValue: '' },
      passwd: { type: DataTypes.STRING, defaultValue: '' },
      tpl: { type: DataTypes.STRING, defaultValue: 'en' }
    },
    {
      hooks: {
        beforeCount(options) {
          options.raw = true;
        }
      },
      classMethods: {
        associate(models) {
          bwebusers.belongsToMany(models.bwebroles, {
            as: 'roles',
            through: 'bweb_role_member',
            foreignKey: 'userid',
            onDelete: 'NO ACTION'
          });
        }
      }
    }
  );

  // eslint-disable-next-line no-unused-vars
  bwebusers.associate = function(models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
    bwebusers.belongsToMany(models.bwebroles, {
      as: 'roles',
      through: 'bweb_role_member',
      foreignKey: 'userid',
      onDelete: 'NO ACTION'
    });
  };

  sequelizeClient.sync();
  return bwebusers;
};

```

```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function(app) {
  const sequelizeClient = app.get('sequelizeClient');
  const bwebroles = sequelizeClient.define(
    'bweb_role',
    {
      roleid: {
        type: DataTypes.BIGINT(20).UNSIGNED,
        autoIncrement: true,
        primaryKey: true,
        unique: true
      },
      rolename: { type: DataTypes.STRING(100), allowNull: false, unique: true },
      comment: { type: DataTypes.STRING, defaultValue: '' }
    },
    {
      hooks: {
        beforeCount(options) {
          options.raw = true;
        }
      },
      classMethods: {
        associate(models) {
          bwebroles.belongsToMany(models.bwebusers, {
            as: 'roles',
            through: 'bweb_role_member',
            foreignKey: 'roleid',
            onDelete: 'NO ACTION'
          });
        }
      }
    }
  );

  // eslint-disable-next-line no-unused-vars
  bwebroles.associate = function(models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
    bwebroles.belongsToMany(models.bwebusers, {
      as: 'users',
      through: 'bweb_role_member',
      foreignKey: 'roleid',
      onDelete: 'NO ACTION'
    });
  };
  sequelizeClient.sync();

  return bwebroles;
};

```

**Comment by honzahommer** [comment]
In associations you have references to non existing models.
- model.bwebusers instead of model.bweb_user
- model.bwebroles instead of model.bweb_role
