### ISSUE TITLE
error: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by alexandrmiee** [feathersjs-ecosystem/feathers-sequelize#294]
I have 2 models in one to one relationship

```js
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const users = sequelizeClient.define('users', {
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    /*...*/
  
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = false;
      }
    }
  });
  users.associate = function (models) {
    console.log('association for users.hasOne.userDescription created')
    const {userDescription} = models;
    const constraints = {
      // as:'Description',
      // foreignKey: 'user_id',
      // sourceKey: 'email',
    }
    users.hasOne(
      userDescription,
      constraints
    );
  };
  return users;
};
```

```js
module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const userDescription = sequelizeClient.define('userDescription', {
    name: {
      type: DataTypes.STRING,
      allowNull: true,
      unique: false
    },
    /*...*/    
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = false;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  userDescription.associate = function (models) {
    console.log('association for userDescription.belongsTo.users 
    const {users} = models;
    const constraints = {
      // as:'Description',
      // foreignKey: 'user_id',
      // sourceKey: 'email',
    }
    userDescription.belongsTo(
      users,
      constraints
    );
  };
  return userDescription;
};
```

hook that run befor create user
```js

module.exports = function (options = {}) {
	return async context => {
        if(context.data.userDescription){
            if (!context.params.sequelize){
                const sequelizeClient = context.app.get('sequelizeClient');
                context.params.sequelize = {
                    raw: false,
                    include:[
                        {association: sequelizeClient.models.userDescription,}
                    ]
                }
            }
        }
        return context;
	};
};
```

and get error when create user

```
error: TypeError: Cannot read property 'name' of undefined
    at Function._conformInclude (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:247:48)
    at options.include.options.include.map.include (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:213:59)
    at Array.map (<anonymous>)
    at Function._conformOptions (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:213:39)
    at new Model (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:3069:24)
    at new users (C:\Web\ArtChat\backend\node_modules\sequelize\lib\sequelize.js:340:19)
    at Function.build (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:1965:12)
    at Function.create (C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:2016:17)
    at Object._create (C:\Web\ArtChat\backend\node_modules\feathers-sequelize\lib\index.js:208:23)
    at callMethod (C:\Web\ArtChat\backend\node_modules\@feathersjs\adapter-commons\lib\service.js:9:20)
    at Object.create (C:\Web\ArtChat\backend\node_modules\@feathersjs\adapter-commons\lib\service.js:64:12)
    at processHooks.call.then.hookObject (C:\Web\ArtChat\backend\node_modules\@feathersjs\feathers\lib\hooks\index.js:56:27)
```

Then I open C:\Web\ArtChat\backend\node_modules\sequelize\lib\model.js:247:48 and see condition
```js
if (self && include.association.target.name === self.name)
```
'users' association have no any target attribute

What could be the reason?

**Comment by alexandrmiee** [comment]
I change 
`{association: sequelizeClient.models.userDescription,}`
to
`{association: sequelizeClient.models['users'].associations['userDescription']}`
and all worked fine.
But...
Why does it work like this?

**Comment by daffl** [comment]
It is likely that `sequelizeClient.models.userDescription` does not exist and has been named `user_description` or something similar instead. The name is set in `sequelizeClient.define(` in `src/model/modelname.js`

**Comment by alexandrmiee** [comment]
No, it's named 
`const userDescription = sequelizeClient.define('userDescription',`
like in example
