### ISSUE TITLE
queryWithCurrentUser gives NotFound: No record found for id 'null'

### ISSUE THREAD

**Issue by apmcodes** [feathersjs-ecosystem/feathers-sequelize#329]
Using sequelize

Trying to get credit for currently logged in user with queryWithCurrentUser but getting the below error. This has worked in another service but not in this `credit` service. 

Tried setting id field to userId in the credit.service but does not work.
Using **const userField = { idField: 'id', as: 'userId' };**

**Error**
```
error: NotFound: No record found for id 'null'
    at new NotFound (/work/nilbounce/api/node_modules/@feathersjs/errors/lib/index.js:114:17)
    at Model.findAll.then.then.catch.error (/work/nilbounce/api/node_modules/feathers-sequelize/lib/index.js:124:15)
```
**credit.hooks**
```
const authHooks = require('feathers-authentication-hooks');
const userField = { idField: 'id', as: 'userId' };

module.exports = {
    before: {
        all: [authHooks.queryWithCurrentUser(userField)],

```
**credit.model**
```
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        credit: {
            type: DataTypes.INTEGER,
            allowNull: false,
            defaultValue: 0,
        },
        userId: {
            type: DataTypes.INTEGER,
            unique: true,
        }
```
**credit.service**
```
// Initializes the `credit` service on path `/credit`
const createService = require('feathers-sequelize');
const createModel = require('../../models/credit.model');
const hooks = require('./credit.hooks');

module.exports = function (app) {
    const Model = createModel(app);
    const paginate = app.get('paginate');

    const options = {
        id: 'id',
        Model,
        paginate
    };

    // Initialize our service with any options it requires
    app.use('/credit', createService(options));

    // Get our initialized service so that we can register hooks
    const service = app.service('credit');

    service.hooks(hooks);
};


Can someone guide me on this?
```

**Comment by daffl** [comment]
The `queryWithCurrentUser` hook has been deprecated. Upgrade to the latest version of `feathers-authentication-hooks` and `feathers-sequelize` and see https://github.com/feathersjs-ecosystem/feathers-authentication-hooks#migrating-to-v100 for more information.

**Comment by apmcodes** [comment]
Okay sure. Waiting to complete the work with Buzzard and then upgarde to V4.

**Comment by apmcodes** [comment]
Upgraded to V4. Thank you for the guidance. Feels better to be uptodate.
