### ISSUE TITLE
Query by Association

### ISSUE THREAD

**Issue by RickEyre** [feathersjs-ecosystem/feathers-sequelize#373]
It seems like the notation `$nested.query$` is no longer working? I'm getting an error in the `filter-query` adapter commons.

For example:

```js
app.service('my/service').find({
  query: {
    '$related.table$': 4
  }
}
```

Has the API changed for this type of query now?

Thanks.

**Comment by DaddyWarbucks** [comment]
The API has not changed. What error are you receiving?

The below syntax should work
```js
app.service('my/service').find({
  query: {
    '$related.table$': 4
  },
  sequelize: {
    include: [{
      model: relatedModel,
      as: 'related'
    }]
  }
}
```

You do also have to whitelist the `'$related.table$'` property in the service options.

**Comment by RickEyre** [comment]
Thanks for the response. Here is my setup:

```js
context.params.sequelize = {
    raw: false,
    include: [
      { model: V2Statuses, as: 'statuses' }
    ],
    order: [
      [{ model: V2Statuses, as: 'statuses' }, 'occuredAt', 'DESC']
    ]
  }
  ```

HTTP Request:
```
https://mydomain.com/v2/model?$statuses.type$=queued
```

Does it make a difference that this relation is a one too many? As in there are many statuses for one model?

**Comment by RickEyre** [comment]
And the error, sorry:

```shell
 [dev] Error in 'v2/models' service method 'find' BadRequest: Invalid query parameter $statuses.type$
     at new BadRequest (/usr/src/app/node_modules/@feathersjs/errors/lib/index.js:86:17)
     at /usr/src/app/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:45:27
     at /usr/src/app/node_modules/@feathersjs/commons/lib/utils.js:16:45
     at Array.forEach (<anonymous>)
     at Object.each (/usr/src/app/node_modules/@feathersjs/commons/lib/utils.js:16:30)
     at cleanQuery (/usr/src/app/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:39:21)
     at Object.filterQuery [as default] (/usr/src/app/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:91:20)
     at Object.filterQuery (/usr/src/app/node_modules/@feathersjs/adapter-commons/lib/service.js:46:46)
     at Object.filterQuery (/usr/src/app/node_modules/feathers-sequelize/lib/index.js:77:28)
     at Object._find (/usr/src/app/node_modules/feathers-sequelize/lib/index.js:122:54)
     ```

**Comment by DaddyWarbucks** [comment]
You have to whitelist the `$statuses.type$` parameter in the service options.

```js
const options = {
    Model,
    paginate,
    whitelist: ['$statuses.type$']
  };
```

**Comment by RickEyre** [comment]
Awesome, thank you.
